### Site Settings ###
title               : jasongoo827
description         : >-
                      Game & Graphics Developer
baseurl             : ""            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url: "https://jasongoo827.github.io"
repository          : jasongoo827/jasongoo827.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji

### Google Analytics ###
google_analytics: G-GNZM4ZG5RT  # 여기에 실제 측정 ID를 넣으세요


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : jasongoo827
  image             : https://avatars.githubusercontent.com/u/81475273?v=4
# behance           : your_username
# dribbble          : your_username
  email             : jasongoo@naver.com
# facebook          : your_username
  github            : jasongoo827
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : jae-woo-goo-38bba5353
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
  youtube           : koo
# keybase           : your_username


### Posts ###
permalink: /blog/:title
future: true


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  comments: true
  shortname: jasongoo827                   # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - vendor
